### ISSUE TITLE
Question: PreparedBatch in pgnio

### ISSUE THREAD

**Issue by smahad786** [cretz/pgnio#11]
I am able to use the prepareReusable() together with reusePrepared() and was able to run a select query for a List of Keys in a postgres table. However, I wanted something like preparedBatch() where I can provide all the values in where clause (like in a List<Tuple>) and run a preparedBatch query [just like in pg reactive client] without the need for using reusePrepared().

How can I achieve the equivalence of preparedBatch()...

**Comment by cretz** [comment]
From a quick glance at their code, the equivalent would be first calling `prepare` (don't need `prepareReusable` because that's only for referencing one by name later, not for one you are using right away), `describe` to get result column info if you want it, and then calling `bindExecuteAndBack` over and over until the last one which would be `bindExecuteAndDone` (those are just combined shortcut methods, you could call the pieces individually e.g. calling `bind`, then `execute`, and then either `back` for more or `done` when through...or just `done` after the loop, it doesn't have to be combined with `execute` and can be done after a `back`).

Let me know if this doesn't make sense.

**Comment by cretz** [comment]
@smahad786 - Please let me know if this sufficiently answered your question so I can close the issue.

**Comment by cretz** [comment]
Closing assuming the question was answered. Please comment if there is more information I can provide.
