### ISSUE TITLE
Question: Query & Connection TimeOut 

### ISSUE THREAD

**Issue by smahad786** [cretz/pgnio#12]
There are 2 timeout parameters - one in the Config() and other with the withConnection(). I understood the following:
the conn time out in Config() is related to Query Timeout and the timeout with withConnection is the connection timeout. Is this correct?

**Comment by cretz** [comment]
Not exactly.

Config.defaultTimeout says in the Javadoc: "The default timeout [...] for all async reads and writes.". It is literally what is passed to channel [reads](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousSocketChannel.html#read-java.nio.ByteBuffer-long-java.util.concurrent.TimeUnit-A-java.nio.channels.CompletionHandler-) and [writes](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousSocketChannel.html#write-java.nio.ByteBuffer-long-java.util.concurrent.TimeUnit-A-java.nio.channels.CompletionHandler-)

ConnectionPool.withConnection says in the Javadoc: "Invoke the function with a borrowed connection or throw if timeout reached waiting for one." That means the timeout is just for waiting for a connection in the pool. It also says in the Javadoc: "This is a simpler alternative to borrowConnection() + returnConnection(QueryReadyConnection.AutoCommit)" and on the borrowConnection Javadoc: "If a connection is not available, this blocks until one is made available or the timeout is reached (which throws an IllegalStateException).".

Postgres doesn't have a concept of query timeout. You can always timeout on the application side and cancel the query or close the connection.

Java NIO doesn't have the concept of a connection timeout. [open](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousSocketChannel.html#open--) and [connect](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousSocketChannel.html#connect-java.net.SocketAddress-A-java.nio.channels.CompletionHandler-) don't accept timeouts. But it doesn't really matter because the connection auth happens which uses read/write so it leverages those timeouts.

I hope that clears things up. Let me know if it doesn't make sense.

**Comment by smahad786** [comment]
Thank you very much. I did not understand the concept of defaulttimeout in Config. I appreciate your timely response.

**Comment by cretz** [comment]
Closing assuming the question was answered. Please comment if there is more information I can provide.
